### PR TITLE
[Feature: #112322007] Feature/Episode Page

### PR DESCRIPTION
**Pull request by johnkariuki**
Enable each episode to have a unique page and provide the link in facebook and twitter posts.

### CODE REVIEW

**Comment by unicodeveloper** [comment]
It had a problem deploying, check the heroku dashboard, it has failed to deploy. Check out the reason behind that and fix.

**Comment by unicodeveloper** [comment]
There are also lots of conflicts, rebase and resolve.

**Comment by johnkariuki** [comment]
I have deployed and it works from my end.
Try deploying again, click on one of the episodes and try either the twitter share option.

**Comment by johnkariuki** [comment]
The facebook share may not work until merged into staging since the facebook app ID IS explicitly set to http://suyabay-staging.herokuapp.com.

**Comment by johnkariuki** [comment]
I am looking into the merge conflicts now.

**Pull request merged**
