### PR TITLE
(fix) Fix migrations and tests conflict

### PR DESCRIPTION
**Pull request by vickris**
Commented out roles in the roles table and also debugged tests to make sure all were passing

### CODE REVIEW

**Comment by unicodeveloper** [comment]
Why are the tests still failing?

**Comment by vickris** [comment]
they pass locally...not sure whats  going on with travis

**Comment by unicodeveloper** [comment]
Check the travis environment setting. It's still trying to connect to a database on Laravel forge. Meanwhile, we are using a dbsqlite file, so you should stop it from connecting to any database. Check your `.travis.yml` file too. These are snapshots from travis indicating that we still have an env variable for DB set to `pgsql`

screen shot 2016-01-12 at 7 15 20 am

screen shot 2016-01-12 at 7 15 54 am

screen shot 2016-01-12 at 7 16 05 am

**Comment by vickris** [comment]
ok lemme fix that

**Comment by vickris** [comment]
build is now passing

**Comment by unicodeveloper** [comment]
Awesome. Good job! :green_apple:

**Comment by vickris** [comment]
thank you

**Pull request merged**
