### PR TITLE
[Chore #114804635] Add mime type detection

### PR DESCRIPTION
**Pull request by vickris**
Added mime type detection so that people using phones or browsers that don't support HTML5 won't upload files which are not audio files. Validation for file uploads had been done using HTML5 initially.

### CODE REVIEW

**Comment by unicodeveloper** [comment]
We don't need all of this. You just need to figure out the right apache .mp3, .m4a, .mp4 mime types and use the laravel mime validation like so:

screen shot 2016-03-02 at 4 51 49 pm

**Comment by unicodeveloper** [comment]
For the tests, we don't need to upload real files, we can mock that functionality and use a stub instead. @andela-cvundi

**Comment by vickris** [comment]
@unicodeveloper sorry for the late reply. Just seeing this now. Cool, I will use stubs.

**Comment by unicodeveloper** [comment]
@andela-cvundi what's the latest on this?.. have you replaced the Mime class with laravel's mime validation filter?

**Comment by vickris** [comment]
@unicodeveloper Yeah. Let me push my latest changes. Sorry, I thought I shouldn't push when the tests are for the feature are not passing. Will do away with the tests in the meantime.

**Comment by vickris** [comment]
Just pulled from staging and the one of the tests in the CommentsTest is failing. I will just have to hold back till Temitope fixes that so I can pull from staging again

**Comment by unicodeveloper** [comment]
Instead of holding back, rally with @andela-tolotin and help fix the issue so that everyone can proceed faster.

**Comment by vickris** [comment]
You can merge the branch now

**Pull request merged**
