### PR TITLE
#115754921 Comment count should be displayed below episodes

### PR DESCRIPTION
**Pull request by vickris**
#### What does this PR do?
- Initially, the comment count was not displayed below episodes in the various pages. I fixed that and now one can see the number of comments for a particular episode
#### Description of Task to be completed?
- Create an icon for the comments
- Fetch the number of comments for each episode and display the number next to the comments icon
#### How should this be manually tested?
- Comment on an episode.
- You should notice that the comment count increased by one
#### What are the relevant pivotal tracker stories?
#115754921

### CODE REVIEW

**Comment by unicodeveloper** [comment]
When you comment on an episode, you shouldn't have to refresh the page for the comment count to reflect the new comment, it should update asynchronously. @andela-cvundi Please fix that

**Comment by vickris** [comment]
Okay lemme fix that asap

**Comment by unicodeveloper** [comment]
Your builds are failing. Please fix @andela-cvundi

**Comment by unicodeveloper** [comment]
This issue has still not been fixed @andela-cvundi . Whats the progress on this?

**Comment by vickris** [comment]
@unicodeveloper I was having merge conflicst but finally resolved them.

**Pull request merged**
