### PR TITLE
[feature #113846287] View comments on single episode has been fixed

### PR DESCRIPTION
**Pull request by olotintemitope**
Comments on the single episode now display 10 comments on page load without having to click on view comments. It also features view comments link, which allows the user to load more comments at will.

### CODE REVIEW

**Comment by johnkariuki** [comment]
@andela-tolotin Your pull request name should be in imperative format e.g Fix view comments on single episode.

Refer to the wIki page.

**Comment by unicodeveloper** [comment]
@andela-tolotin What's the status on this?

**Comment by olotintemitope** [comment]
@unicodeveloper I am working on @andela-jkariuki suggestion as regards the commit message and  also, the merge pull request issue raised by GitHub.

**Comment by olotintemitope** [comment]
@unicodeveloper I have implemented it.

**Comment by unicodeveloper** [comment]
Please rebase to resolve the merge conflicts @andela-tolotin

**Comment by olotintemitope** [comment]
Okay, I'm on it

**Comment by olotintemitope** [comment]
@unicodeveloper I have resolved the merge conflict on my branch

**Comment by unicodeveloper** [comment]
Why did you merge it into staging @andela-tolotin ? :angry:  :red_circle:

**Pull request merged**
