### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by fokosun**

### CODE REVIEW

**Comment by fokosun** [comment]
comment

**Comment by unicodeveloper** [comment]
I appreciate the fact that you decided to tackle the issue but never you push directly to `master` and `staging` branches!. I specifically told the team that no one should push directly to `staging` and `master`. When you work on a feature/hotfix, submit a pull request against the `staging` branch, then i'll review it.

**Comment by unicodeveloper** [comment]
You also broke the build. All checks are failing!. The `master` branch doesn't have a `.travis.yml` file. As regards this project, please don't ever push directly to `master` or `staging` branch. I also need you to rename your branch. `andela-fokosun-patch-1` is not appropriate :-1: . Let it be something like `issue/readme` or `hotfix/readme` . I'll therefore close this PR!. Submit another PR after making the corrections.

**Comment by unicodeveloper** [comment]
I'll rollback the changes to `master` branch.

**Pull request closed without merging**
