### PR TITLE
[Feature: #111509412] User-profiles 

### PR DESCRIPTION
**Pull request by vickris**
This feature allows users to update their usernames and avatars and also change passwords if logged in

### CODE REVIEW

**Comment by unicodeveloper** [comment]
1. There are no tests for this, please write tests for these functionalities.
2. I can't change my avatar, this is what i get

screen shot 2016-01-19 at 2 53 39 pm

The display of the error/success messages is not really appealing, it could be finer and better, ask @andela-fokosun if you need design inspiration

screen shot 2016-01-19 at 2 57 11 pm

screen shot 2016-01-19 at 2 55 44 pm

**Comment by vickris** [comment]
Okay will look into the tests and the ui

**Comment by unicodeveloper** [comment]
What's the status on this @andela-cvundi ?

**Comment by vickris** [comment]
sending a pull request before the day ends

**Pull request merged**
