### PR TITLE
[Chore #113466467] New Favicon have been uploaded

### PR DESCRIPTION
**Pull request by ademola-raimi**
I deleted all the unused images and uploaded a new image. The newly uploaded image was used as the Favicon. The image below displays the newly uploaded image:

screen shot 2016-02-22 at 5 59 04 pm

screen shot 2016-02-22 at 6 10 31 pm

### CODE REVIEW

**Comment by unicodeveloper** [comment]
This present favicon image file does not in anyway fit the theme of this project. The colors are out of place ( the background and foreground) and it's overall look is not appealling at all. Please consult/pair with @andela-fokosun if you need help with making a better favicon

**Comment by ademola-raimi** [comment]
The repeated block of codes was due to the fact that some pages does not extend from the master blade. The login, sign up and the settings pages have different pages they extend from. I have to search for the pages and put the link in order for the favicon to display across all the pages in suyabay.

 I have changed the directory of the ICO file to its normal position.

Finally, I am currently working with someone to have the favicon redesigned.

**Comment by unicodeveloper** [comment]
Why does the login, sign up and settings page extend from different pages?. I need you to make them all extend from one page without breaking any other thing

**Comment by unicodeveloper** [comment]
Always use present tense (imperative form) in your commit messages and PR titles

**Comment by unicodeveloper** [comment]
Can I see a screenshot of the new favicon @andela-araimi  ?

**Pull request merged**
