### PR TITLE
[Chore: #113435705] Increase podcast upload size limit

### PR DESCRIPTION
**Pull request by vickris**
Increase the size limit for uploading mp3 files to 10MB

### CODE REVIEW

**Comment by unicodeveloper** [comment]
What's the latest on this @andela-cvundi ?

**Comment by vickris** [comment]
I closed the old pull request and opened up a new one so that I could generate a new review app on heroku........now that the one with PR 163 wasn't updating @unicodeveloper

**Comment by unicodeveloper** [comment]
So does this current PR generate a build and show effected changes @andela-cvundi ?

**Comment by vickris** [comment]
I get an error every time I click on create review app for that PR on Heroku..
screen shot 2016-02-22 at 10 04 05 am

**Comment by unicodeveloper** [comment]
But you shouldn't have to create a review app manually, if you send in a new PR..it should do that automatically for you.

**Comment by vickris** [comment]
Yeah it should, but then when I visit the dashboard I am seeing that I have to click the create new review app button for that PR
screen shot 2016-02-22 at 10 15 09 am

**Comment by unicodeveloper** [comment]
What's the status on this @andela-cvundi ?

**Pull request closed without merging**
