### PR TITLE
(Chore)[#115116007] Tests user routes, controllers, model and repositories.

### PR DESCRIPTION
**Pull request by johnkariuki**
Write tests to assert that  an administrator
1. Can get the number of users on suyabay
2. Can manger User invites
3. Can manager User roles.

Write tests to assert all UserRepository methods.

### CODE REVIEW

**Comment by andela-oadebayo** [comment]
Remove the funny variable
Good Job.

**Comment by johnkariuki** [comment]
@andela-oadebayo Removed unused variable. 
PR is ready for merging.

**Comment by johnkariuki** [comment]
@unicodeveloper Discussed changes on unused variables have been fixed.
PR is good for merging.

**Comment by unicodeveloper** [comment]
Please rebase @andela-jkariuki

**Comment by johnkariuki** [comment]
@unicodeveloper 
I have rebased and fixed all merge conflicts.

**Pull request merged**
