### PR TITLE
[Suyabay][#106017266][SiteLogo]

### PR DESCRIPTION
**Pull request by fokosun**

### CODE REVIEW

**Comment by unicodeveloper** [comment]
Your commit messages are bad!..Fix it and resolve all the conflicts

**Comment by unicodeveloper** [comment]
@andela-fokosun what's happening here?. why has this not been resolved?

**Comment by unicodeveloper** [comment]
@andela-fokosun what's happening here once again?

**Comment by fokosun** [comment]
I created another branch all together and made all the modifications on the new branch.

**Pull request closed without merging**
