### PR TITLE
[Bug #113466661] Adjustment in the Navbar dropdown setting fixed

### PR DESCRIPTION
**Pull request by ademola-raimi**
Navbar dropdown setting has been changed from:

screen shot 2016-02-16 at 3 52 53 pm

to:

screen shot 2016-02-18 at 11 30 29 am

### CODE REVIEW

**Comment by unicodeveloper** [comment]
The title of your PR should include the Pivotal story ID for this task. Please check the wiki for the right format. Same applies to your commit, it should be labeled as either `chore`, or `fix` or `feature` and should also have the story ID included. Check the wiki for the right format for writing commit messages and amend the commit @andela-araimi

**Comment by unicodeveloper** [comment]
Please make use of just `Profile` and `Account` as labels in the dropdown. Remove the `settings` beside it to avoid tautology ( repetition)

**Comment by unicodeveloper** [comment]
Your last commit didn't make a build? I still see the `Settings` on the two labels

screen shot 2016-02-22 at 7 45 45 am

**Comment by unicodeveloper** [comment]
ping @andela-araimi

**Comment by ademola-raimi** [comment]
I will find out why and get back to you.

**Pull request merged**
