### PR TITLE
Feature/user registrationand authentication

### PR DESCRIPTION
**Pull request by emeka-osuagwu**

### CODE REVIEW

**Comment by unicodeveloper** [comment]
Please fix your commit messages to follow the right format and then rebase

**Comment by unicodeveloper** [comment]
What's happening here?..haven't seen any activity on this yet

**Comment by emeka-osuagwu** [comment]
Fixed

**Comment by unicodeveloper** [comment]
What happened to the evil commit messages I told you to amend? I still see ugly, inconsistent and grammatical blunder infected commit messages. Fix!. We need to have gone past this stage, you are holding us back

**Comment by unicodeveloper** [comment]
rebase

**Pull request closed without merging**
