### PR TITLE
Comments and code cleanup

### PR DESCRIPTION
**Pull request by vickris**
Noticed that most of the crud functions in the controllers are empty. I am still getting hold of laravel and I am not sure if there's a before action to provide content to these empty  functions.

### CODE REVIEW

**Comment by unicodeveloper** [comment]
Please rewrite your commit to follow the commit standard for this project. I posted the format in the slack group

**Comment by unicodeveloper** [comment]
Also, let your pull request title follow the right format

**Comment by vickris** [comment]
Noted. Will observe the agreed upon rules in my preceeding commits

On Tue, Dec 15, 2015 at 5:33 AM, Prosper Otemuyiwa <notifications@github.com

**Comment by unicodeveloper** [comment]
Yeah..but i need you to rebase and fix this present one by rewriting it

**Comment by vickris** [comment]
Hi,
what do you mean by rebase?

On Tue, Dec 15, 2015 at 2:03 PM, Prosper Otemuyiwa <notifications@github.com

**Comment by unicodeveloper** [comment]
Check this out [https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request)

**Pull request closed without merging**
