### PR TITLE
[feature #113846287] Fix on episode comments display

### PR DESCRIPTION
**Pull request by olotintemitope**
I have implemented view episode comments on the single episode page. Initially, when the page loads it fetches 10 comments, users can later load more comments by clicking on view more comments links.

### CODE REVIEW

**Comment by unicodeveloper** [comment]
Please fix the Nitpick-CI and HoundCI issues ASAP!

**Comment by olotintemitope** [comment]
I have fixed  the Nitpick-CI and HoundCI issues.

**Comment by unicodeveloper** [comment]
Is this ready to be merged?..What's the latest on this?

**Comment by olotintemitope** [comment]
@unicodeveloper, it is ready to be merged

**Pull request merged**
